/* This code generated by the wonderful http://t-filter.appspot.com */

#include <fir.h>

static double filterTaps[] = {-0.07951087685285016,
                               0.01945354671754785,
                              -0.005453575732499895,
                              -0.04837063849132621,
                              -0.07168597959153167,
                              -0.16374206778816897,
                               0.7588178512425175,
                              -0.16374206778816897,
                              -0.07168597959153167,
                              -0.04837063849132621,
                              -0.005453575732499895,
                               0.01945354671754785,
                              -0.07951087685285016};

void firInit(Fir *f)
{
    for (int i = 0; i < sizeof(filterTaps) / sizeof(filterTaps[0]); ++i) {
        f->history[i] = 0;
    }
    f->lastIndex = 0;
}

void firPut(Fir *f, double input)
{
    f->history[f->lastIndex] = input;
    f->lastIndex++;

    if (f->lastIndex == sizeof(filterTaps) / sizeof(filterTaps[0])) {
        f->lastIndex = 0;
    }
}

double firGet(Fir *f)
{
    double acc = 0;
    int index = f->lastIndex;

    for (int i = 0; i < sizeof(filterTaps) / sizeof(filterTaps[0]); ++i) {
        if (index != 0) {
            index = index - 1;
        } else {
            index = sizeof(filterTaps) / sizeof(filterTaps[0]) - 1;
        }
        acc += f->history[index] * filterTaps[i];
    }

    return acc;
}